bind 0.0.0.0
protected-mode no
port 6379

appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# Lưu dữ liệu định kỳ (snapshot RDB)
# Mỗi dòng phải không có comment phía sau
save 900 1
save 300 10
save 60 10000