### config profile spring
spring.profiles.active=production
spring.application.name=Profiles
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
server.port=8085
server.address=0.0.0.0
### context path
server.servlet.context-path=/
### config thymeleaf
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
### config session time out
server.servlet.session.timeout=60m
### config tomcat
server.tomcat.accesslog.enabled=false
server.tomcat.basedir=/tmp
server.use-forward-headers=true
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto
### Thread pool manager
threadpoll.corePoolSize=5
threadpoll.maxPoolSize=10
threadpoll.keepAliveSeconds=10000
threadpoll.queueCapacity=10000000
threadpoll.allowCoreThreadTimeOut=true
### config logging level
logging.level.root=warn
logging.level.org.springframework.boot=info
logging.level.org.springframework.web=info
logging.level.org.springframework.security=info
logging.level.org.springframework.jdbc=debug
logging.level.org.hibernate=info
logging.level.vn.co.cake=info
logging.level.org.springframework.data.jpa.repository: DEBUG
spring.jpa.open-in-view=true

# jwt
jwt.secure.secret=qaX1lZDjBe8KRi2Hr4iSbepomV4nbzuoEaUKipiceA0BsfCzl8zUgcfmmqEdt9jp

#spring.jpa.open-in-view=false
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.file-size-threshold=20MB

spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**

# Load static từ cả JAR và thư mục ngoài
spring.web.resources.static-locations=classpath:/static/,file:/var/www/html/images/
spring.mvc.static-path-pattern=/**

# Bật nén response
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024



