### database
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# postgres connect
spring.datasource.url=jdbc:postgresql://cake-store.cluster-cxea6wgcyobr.ap-southeast-1.rds.amazonaws.com:5432/cake-store
#spring.datasource.url=jdbc:postgresql://10.99.63.126:5432/comas_test
spring.datasource.username=postgres
spring.datasource.password=Pickgunny123
# Hikarin
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.initialization-mode=always
spring.datasource.hikari.initialization-fail-timeout=10000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.pool-name=ConnPool
### Mail service
# SMTP
spring.mail.host=smtp-relay.gmail.com
spring.mail.port=587
# Mail no reply
mail.noreply.address=haitv@ominext.com
#remember me timout
remember-me.session.timeout=1296000
server.servlet.session.timeout=15d

cake.base.url-sa=http://localhost:8080/SA/SA001/login
cake.base.url=http://localhost:8080

pancake.pos.api.url=https://api.pancake.vn
pancake.pos.api.token=33cab124800142cd859bb93b0b52aa79

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

aws.s3.image=cake-product-bucket

